.github/workflows/build.yml
main 브런치에 푸시 혹은 PR 생성시 CI를 작동합니다.
=> Build CI 추가

src/constants/roomMessage.ts, src/pages/rooms/[roomId].tsx, src/service/RoomSocketService.ts, src/stores/RoomStore.ts, test/RoomStore.test.ts
https://user-images.githubusercontent.com/57604817/217730625-cd01c2f8-291c-4112-9721-45964c95a55f.mov
=> [CFRS-84] 이미 접속한 공부방에 또 접속할 수 없도록 수정

src/constants/image.constant.ts, src/constants/message.ts, src/controller/user.controller.ts, src/pages/welcome.tsx, src/utils/user.validator.ts, test/WelcomeStore.test.ts, test/user.model.test.ts
프로필 이미지 확장자, 크기를 확인합니다.
확장자는 jpg, jpeg, png가 가능하고, 크기는 최대 5MB입니다.
=> [CFRS-44] profile-image validation check

src/constants/socketProtocol.ts, src/models/room/JoinRoomFailureCallbackProperty.ts, src/models/room/JoinRoomSuccessCallbackProperty.ts, src/models/room/WaitingRoomData.ts, src/pages/rooms/[roomId].tsx, src/service/RoomSocketService.ts, src/stores/RoomStore.ts, test/RoomStore.test.ts
대기실에서 입장 버튼을 누르면 소켓 서버에 정보를 보내 아래의 사항을 검증합니다.
- 비밀번호 일치
- 블랙리스트 포함 여부
- 방 인원 가득 찼는지 여부(방장은 무시)
아래의 PR에서 실제 검증 코드를 확인할 수 있습니다.
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/7
https://user-images.githubusercontent.com/57604817/218006231-77930730-5bae-4560-bfbc-686756040c63.mov
=> [CFRS-73] 대기실 방 비밀번호 입력 기능 구현 및 입장 검증 로직 추가

package-lock.json, src/constants/user.constant.ts, src/controller/user.controller.ts, src/models/user/InitialInformationRequestBody.ts, src/models/user/User.ts, src/models/user/UserGetRequestBody.ts, src/pages/api/users/[userId].ts, src/pages/api/users/[userId]/profile-image.ts, src/pages/index.tsx, src/pages/login.tsx, src/repository/user.repository.ts, src/service/user.service.ts, src/stores/UserStore.ts
회원 정보 조회하는 기능입니다.
현재 id, name 조회 가능합니다.
로그인 후 index 페이지에서 getUserInformation버튼을 누르면 콘솔창에서 확인 가능합니다.
=> [CFRS-83] 회원 정보 조회 기능 구현

src/controller/room.controller.ts, src/models/room/RoomOverview.ts, src/models/room/RoomsRequestGet.ts, src/pages/rooms.tsx, src/repository/room.repository.ts, src/service/room.service.ts, src/stores/RoomListStore.tsx, src/utils/rooms.validator.ts, test/RoomCreateRequestBody.test.ts
- 방 개설 시 유효 기간을 임시적으로 만든 날짜의 이틀 뒤로 설정
- 방 조회 버튼 클릭 시 방 이름과 각 방의 (현재 인원 / 최대 인원) 출력
=> [CFRS-87] 방 유효 기간, 인원 수 값 추가

src/constants/socketProtocol.ts, src/models/room/JoinRoomSuccessCallbackProperty.ts, src/models/room/PeerState.ts, src/pages/rooms/[roomId].tsx, src/service/RoomSocketService.ts, src/stores/RoomStore.ts, test/RoomStore.test.ts
아래의 영상을 보시면 사파리에서 딜레이가 존재합니다. 아직 원인을 찾지 못하여 나중에 문제가 되면 수정해야 할 듯 합니다.
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/10
https://user-images.githubusercontent.com/57604817/218665362-c34d86cd-24d5-4426-bd96-34a95955d658.mov
=> [CFRS-96] 공부방에서 상대의 미디어 상태 아이콘 보이는 기능 추가

next.config.js, prisma/schema.prisma, src/constants/roomMessage.ts, src/controller/room.controller.ts, src/models/room/RoomDeleteRequestBody.ts, src/models/room/RoomOverview.ts, src/models/room/RoomsGetRequest.ts, src/pages/api/rooms/[roomId].ts, src/pages/rooms.tsx, src/repository/room.repository.ts, src/service/room.service.ts, src/stores/RoomListStore.tsx, src/utils/rooms.validator.ts
- 로그인 정보가 있을 경우에만 /rooms 페이지에 접근 가능하도록 변경
- 방 조회 시 deleted_at 값이 null 인 방만 보여주도록 변경
- 본인이 방장인 방에만 x버튼 표시, x 클릭 시 방 삭제
https://user-images.githubusercontent.com/56541313/218681024-0e752209-8dd0-41a1-9762-73ce97e7e4ab.mov
=> [CFRS-21] 방 삭제 기능 추가

src/constants/room.constant.ts, src/constants/roomMessage.ts, src/controller/room.controller.ts, src/models/room/RecentRoomsGetRequest.ts, src/pages/api/users/[userId]/recent-rooms.ts, src/pages/rooms.tsx, src/repository/room.repository.ts, src/service/room.service.ts, src/stores/RoomListStore.tsx, src/utils/user.validator.ts
- 방 삭제 시 확인 메세지 추가
- 버튼 클릭 시 최근 입장한 방을 최신순으로 출력
https://user-images.githubusercontent.com/56541313/218966054-fe95c001-dd16-41c5-b20f-72aea6a301ed.mov
=> [CFRS-20] 최근 입장한 방 조회 

src/constants/socketProtocol.ts, src/pages/index.tsx, src/pages/rooms/[roomId].tsx, src/service/RoomSocketService.ts, src/service/user.service.ts, src/stores/RoomStore.ts, test/RoomStore.test.ts
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/12
동영상에는 깜빡했는데 차단 후에는 아래와 같이 차단 되어 접속 불가합니다!
https://user-images.githubusercontent.com/57604817/219286690-e4c78345-2ef1-46b0-8f06-2a83d131e0b3.mov
=> [CFRS-78] 공부방 회원 차단 추가 기능 구현

package-lock.json, package.json, src/components/RoomSettingDialog.tsx, src/constants/socketProtocol.ts, src/models/room/BlockedUser.ts, src/models/room/WaitingRoomData.ts, src/pages/rooms/[roomId].tsx, src/service/RoomSocketService.ts, src/stores/RoomStore.ts, test/RoomStore.test.ts
- 임시적으로 Material UI의 다이어로그를 이용했습니다.
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/13
https://user-images.githubusercontent.com/57604817/219385386-120b7950-633e-4eb0-a44b-12f04dfeb7b6.mov
=> [CFRS-79] 회원 차단 해제 기능 구현

package-lock.json, package.json, src/components/SendEmail.tsx, src/constants/organizationMessage.ts, src/controller/organization.controller.ts, src/models/common/Result.ts, src/models/organization/OrganizationsEmailRequestBody.ts, src/pages/api/organizations/[organizationId].ts, src/pages/organizations.tsx, src/repository/organization.repository.ts, src/service/organization.service.ts, src/service/room.service.ts, src/stores/OrganizationStore.tsx, src/utils/organizations.validator.ts, test/RoomCreateRequestBody.test.ts
- 소속명 입력 시 유사한 학교/회사명 출력
- 출력된 단체명 클릭 시 input 값 해당 값으로 변경
- 존재하는 소속명 선택 시에만 이메일 발송 버튼 생성
- 이메일 입력 후 발송 버튼 클릭 시 해당 이메일로 인증 메일 발송
https://user-images.githubusercontent.com/56541313/220533042-fb0c9228-4882-45d6-af5a-2cc16b94fe80.mp4
=> [CFRS-105] 소속 조회 및 인증 이메일 발송 구현 (인증 기능 x)

src/constants/socketProtocol.ts, src/pages/rooms/[roomId].tsx, src/service/RoomSocketService.ts, src/stores/RoomStore.ts, src/utils/MediaUtil.ts
- 다른 사람 캠을 누르면 영상이 사라집니다.
- 다시 누르면 보입니다.
- 스토어에 유저가 현재 사용하고 있는 장치 id와 사용할 수 있는 장치 목록을 저장합니다.
- 장치가 추가되거나 제거되면 장치 목록을 갱신해서 스토어에 저장합니다.
- 갱신한 장치 목록에서 현재 사용하고 있는 장치 id가 없으면 사용 중이던 장치가 없어진 것이므로 장치를 바꿔줍니다.
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/14
---
시연 영상 크기가 커서 링크를 남깁니다.
https://www.youtube.com/watch?v=XgqxO8uTQGk
=> [CFRS-76/81] 다른 사람 캠을 안보는 기능, 출력장치를 변경하는 기능 구현

src/service/RoomSocketService.ts
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/15
=> [CFRS-108] JOIN_ROOM 요청시 내용에 회원 정보는 회원 아이디만 포함하도록 수정

src/service/RoomSocketService.ts
안드로이드 소켓 통신 코드 단순화를 위해 전체적으로 매개변수를 단순하게 변경했습니다.
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/16
=> 소켓 통신 매개변수 단순화

src/service/RoomSocketService.ts
헤드셋 구현부에 버그가 상당히 많습니다... 일단 땜빵용으로 버그를 수정했으나 추후에 리팩토링이 필요해보입니다.
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/18
=> [CFRS-109] 대기실에서 헤드셋 끄고 다시 킬때 발생하는 예외 수정

src/pages/rooms/[roomId].tsx, src/stores/RoomStore.ts, src/utils/DateUtil.ts
- 한국 시간이 아닌 경우 발생할 수 있는 문제 수정
- floor를 이용하여 소수점은 버리도록 수정
=> [CFRS-122] 공부방 타이머 시간 잘못 표기되던 문제 수정

src/service/RoomSocketService.ts
해당 버그를 고쳤읍니다... 버그가 끊임없이 발견되네요 
https://jja08111.atlassian.net/browse/CFRS-123
https://user-images.githubusercontent.com/57604817/222957222-8f2bdad6-5da1-46ed-adc7-39505d6ea684.mov
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/21
=> [CFRS-123] 공부방 입장 성공하면 곧바로 소비자 포트 생성하도록 수정

prisma/schema.prisma, src/constants/FriendMessage.ts, src/constants/FriendStatus.ts, src/constants/message.ts, src/controller/friend.controller.ts, src/controller/user.controller.ts, src/models/friend/FriendPostRequestBody.ts, src/models/friend/RequestHistory.ts, src/models/friend/SimilarNamedFriendsGetRequestBody.ts, src/models/user/UserSearchOverview.ts, src/pages/friends.tsx, src/repository/friend.repository.ts, src/repository/user.repository.ts, src/service/Friend.service.ts, src/stores/FriendStore.tsx
- 이름 조회 후 전송 버튼을 누름-> 친구 요청 전송
- 친구 요청을 중복하여 보낼 경우 에러 출력
https://user-images.githubusercontent.com/56541313/223478536-1ff7b8ff-4e70-4d37-8aac-6c902c8ef365.mov
=> [CFRS-23] 친구 요청 전송

src/constants/FriendMessage.ts, src/controller/friend.controller.ts, src/pages/api/users/[userId]/friends.ts, src/pages/friends.tsx, src/pages/organizations.tsx, src/repository/friend.repository.ts, src/repository/user.repository.ts, src/service/Friend.service.ts, src/stores/FriendStore.tsx
- 유저에게 친구 요청을 보낸 기록이 있을 경우 버튼 클릭 시 친구 요청 취소됨.
https://user-images.githubusercontent.com/56541313/223633810-f8c734b7-795b-4239-a9ff-7b488d7d662f.mov
=> [CFRS-155] 친구 요청 삭제 기능

src/controller/user.controller.ts, src/models/user/UserPostRequestBody.ts, src/pages/api/users.ts, src/repository/user.repository.ts, src/service/user.service.ts, src/stores/WelcomeStore.ts, test/WelcomeStore.test.ts, test/user.model.test.ts
1. 이미지 업로드
2. 이미지 업로드 성공으로 얻어진 응답(이미지 url)으로 프로필 생성
1. 프로필 생성
2. 생성에 성공하면 회원 이미지 업로드
=> Fix wrong flow when create user in Welcome page

src/service/RoomSocketService.ts
onProduce 함수의 callback을 호출을 안해서 프로듀서 생성이 완료되지 못해 발생한 문제였습니다......하하
https://github.com/Foundy-LLC/camstudy-webrtc-server/pull/22
=> 공부방 생성자들 작동 안하는 버그 수정

src/constants/FriendMessage.ts, src/controller/friend.controller.ts, src/pages/api/users/[userId]/friend-requests/[friendId].ts, src/pages/friends.tsx, src/repository/friend.repository.ts, src/service/Friend.service.ts, src/stores/FriendStore.tsx
- 친구 요청 목록에서 승인 버튼을 클릭 시 친구 요청을 수락함
https://user-images.githubusercontent.com/56541313/223955371-bbe560fb-d36e-49cf-b78f-c66ee8d4e369.mp4
=> [CFRS-134] 친구 요청 수락

src/pages/welcome.tsx, src/styles/welcome.module.scss
=> 에러 메시지 디자인 적용

src/styles/welcome.module.scss
변경사항: 보더 색깔 백그라운드 색이랑 일치 시키도록 변경
추가사항: 제출버튼 비활성화 디자인 추가
=> 프로필 생성 버튼 디자인 추가 및 수정

src/styles/base/_reset.scss
전역으로 pretendard설정했습니다.
갈무리 폰트 사용하는 것은 해당 페이지에서 스타일 수정하면 될 것 같습니다.
=> [CFRS-152] 폰트 적용 안되던 것 수정

prisma/schema.prisma, src/constants/FriendMessage.ts, src/controller/friend.controller.ts, src/controller/organization.controller.ts, src/models/friend/FriendGetOverviewsBody.ts, src/models/friend/FriendGetRequestsBody.ts, src/models/organization/BelongOrganization.ts, src/models/organization/Organization.ts, src/models/organization/OrganizationVerifyEmailForm.ts, src/models/user/UserOverview.ts, src/pages/api/organizations.ts, src/pages/api/users/[userId]/friends.ts, src/pages/api/users/[userId]/friends/[friendId].ts, src/pages/friends.tsx, src/pages/organizations.tsx, src/repository/friend.repository.ts, src/repository/organization.repository.ts, src/service/Friend.service.ts, src/service/organization.service.ts, src/stores/FriendStore.tsx, src/stores/OrganizationStore.tsx, src/utils/friend.validator.ts, src/utils/rooms.validator.ts
- 친구 목록 조회 버튼을 클릭하면 친구 목록을 출력
- 프로필 사진 /  이름 / 랭킹 점수 / 로그인 상태 순으로 표시
https://user-images.githubusercontent.com/56541313/224633985-4b9e48c8-ced5-4cf4-a11b-b5f2c1684373.mov
=> [CFRS-131] 친구 목록 조회

src/constants/FriendMessage.ts, src/controller/friend.controller.ts, src/pages/api/users/[userId]/friends.ts, src/pages/api/users/[userId]/friends/[friendId].ts, src/pages/friends.tsx, src/repository/friend.repository.ts, src/service/Friend.service.ts, src/stores/FriendStore.tsx
- 친구 목록에서 x버튼 클릭 시 친구 삭제를 할 수 있습니다.
- 친구 요청 취소 , 친구 거절과 마찬가지로 DB의 friend에서 삭제하는 방식이여서 같은 api 경로를 사용했습니다.
https://user-images.githubusercontent.com/56541313/225208049-c71bf3e3-db2d-461e-9e57-9d0f980c85c4.mov
=> [CFRS-165]친구 삭제 기능

src/service/Friend.service.ts, src/service/organization.service.ts, src/service/room.service.ts, src/service/user.service.ts, src/service/welcome.service.ts, src/utils/fetchAbsolute.ts, test/report.controller.test.ts
- fetchAbsolute를 이용하여 환경 변수의 url과 port 번호를 불러옴
- service에서 fetch 요청 시 fetchAbsolute를 거쳐 요청
=> [CFRS-100] fetchAbsolute 추가 / fetch 경로 절대 경로로 변경

src/constants/CropGrade.ts, src/constants/cropMessage.ts, src/controller/crop.controller.ts, src/models/crop/Crop.ts, src/pages/api/crops.ts, src/pages/index.tsx, src/repository/crop.repository.ts, src/service/crop.service.ts, src/stores/CropStore.tsx, src/stores/RootStore.tsx
- 인벤토리 버튼을 클릭하면 재배된 기록이 있는 재배만 출력
https://user-images.githubusercontent.com/56541313/226647852-9878cab3-d73f-4d51-af0e-819b34051b50.mov
=> [CFRS-177] 수확한 작물 조회 구현

src/constants/cropMessage.ts, src/constants/crops.ts, src/controller/crop.controller.ts, src/controller/user.controller.ts, src/models/crop/CropDeleteRequestBody.ts, src/models/crop/CropHarvestRequestBody.ts, src/models/crop/CropIdRequestBody.ts, src/models/crop/CropsGrade.ts, src/pages/api/crops/[cropId].ts, src/repository/crop.repository.ts, src/utils/CropUtil.ts, src/utils/crop.validator.ts
1. 심은 작물이 있는지 확인
2. 수확하려는 작물 ID와 심어져 있는 작물 ID 일치하는지 확인
3. 작물 타입과 심어진 날짜 확인
4. 심어진 날짜부터 수확가능한 날까지 연속 출석일 수 확인
5. 평균 공부시간 계산
6. 작물 수확 날, 등급 업데이트
=> [CFRS-143] 과일 수확하는 API구현

src/repository/friend.repository.ts
- 친구 수락 api가 요청자, 응답자를 바꾸어 두개 생성하는 걸로 수정됐으므로 삭제 api 또한 양쪽 다 삭제하는 걸로 수정
=> [CFRS-185] 친구 삭제 api 수정

src/repository/friend.repository.ts
- repository에 friend의 accepted를 조회하는 쿼리 추가하여 accepted가 false일 경우 한개만 삭제, true일 경우 양쪽 다 삭제하는 걸로 변경하였습니다.
=> [CFRS-192] 친구 요청 취소 수정

src/controller/organization.controller.ts, src/controller/room.controller.ts, src/models/organization/OrganizationsBelongConfirmRequestBody.ts, src/service/organization.service.ts, src/service/room.service.ts, src/stores/RoomListStore.tsx
- 방 썸네일 사진 설정, 방 삭제, 소속 삭제 api 수정했습니다.
=> [CFRS-190] 매개변수 api 명세서와 일치하도록 수정

package-lock.json, package.json, prisma/schema.prisma, src/components/SideMenuBar.tsx, src/pages/_app.tsx, src/pages/_document.tsx, src/pages/index.tsx, src/pages/login.tsx, src/pages/rooms.tsx, src/pages/welcome.tsx, src/styles/base/_reset.scss, src/styles/sideMenuBar.module.scss
=> [CFRS-188] 사이드 메뉴 바 구현

package-lock.json, package.json, src/pages/rooms.tsx, src/stores/RoomListStore.tsx, src/styles/room-list.module.scss
- 테스트용 ui 삭제
- 방 목록 ui 수정
- 무한 스크롤 구현
https://user-images.githubusercontent.com/56541313/229446530-0d5c13dc-9dcb-4cb6-aa08-41c8acc1950b.mp4
(영상은 기능을 보여주기 위해 8개씩 보여주는 걸로 촬영했습니다.)
=> [CFRS-193] 방 목록 무한 스크롤 구현 / UI 수정

src/styles/color/_colorPalette.scss
이름 형식이나 구현 방식이 어떤 게 효율적일지 의견 주시면 감사하겠습니다 !
=> [CFRS-196] colorPalette 수정

src/styles/base/_reset.scss, src/styles/room-list.module.scss
=> 방 목록 컴포넌트 높이 가변적으로 바꿈

src/controller/room.controller.ts, src/models/room/RoomsGetRequest.ts, src/repository/room.repository.ts
기존 방 목록 GET API에 방 검색기능을 추가하였습니다.
=> [CFRS-210] Implement room querying feature

src/components/ThemeModeToggleButton.tsx, src/styles/darkModeToggleButton.module.scss, src/styles/room-list.module.scss
기존
https://user-images.githubusercontent.com/56541313/230729821-772b38da-ab47-4bf4-b128-0cc0d811fe3e.mov
->
수정 후
https://user-images.githubusercontent.com/56541313/230729996-bbf431b0-ef3e-4315-8f60-a092bd976a3d.mov
=> [CFRS-209] 새로고침 시 버튼 애니메이션 재생되는 문제 해결

src/components/Layout.tsx, src/pages/index.tsx, src/pages/rooms.tsx
헤더랑 사이드바 메뉴 레이아웃 컴포넌트로 따로 뺐습니다.
=> [CFRS-211] 레이아웃 적용

src/controller/friend.controller.ts, src/repository/friend.repository.ts, src/repository/user.repository.ts, src/service/friend.service.ts, src/stores/FriendStore.ts
- maxPage 값을 추가하여 반환하는 것으로 수정하는 과정에서 배열로 반환하도록 잘못 수정한 것을 '키:밸류' 형식의 객체로 전달하는 것으로 수정
- 프론트도 이에 맞춰서 수정
=> [CFRS-222] 회원 검색 GET, 친구 목록 GET API 반환 값 수정

src/constants/message.ts, src/controller/friend.controller.ts, src/controller/user.controller.ts, src/models/user/AmendUserRequestBody.ts, src/models/user/UpdateUserRequestBody.ts, src/models/user/User.ts, src/pages/api/users.ts, src/pages/api/users/[userId].ts, src/pages/profile.tsx, src/pages/users/[userId].tsx, src/repository/user.repository.ts, src/service/profile.service.ts, src/stores/ProfileStore.ts, src/stores/RootStore.ts, src/styles/profile.module.scss, src/utils/user.validator.ts
- 프로필 편집 테스트용 UI
- 프로필 편집 API 구현
https://user-images.githubusercontent.com/56541313/232366103-f1260b2f-c2e8-4099-a094-2353aa4e840a.mp4
=> [CFRS-216] 프로필 편집 UI

src/controller/crop.controller.ts, src/repository/crop.repository.ts
- 성장중인 작물이 있는 회원이 작물을 심고나서 수확 기간까지 공부를 하나도 안한 경우(공부 기록이 없음) 서버 내부에러가 발생하던 문제를 수정했습니다.
- 코드를 개선했습니다.
=> 성장중인 작물 서버 내부에러 수정 및 코드 개선

src/components/SendEmail.tsx, src/controller/organization.controller.ts, src/pages/organizations.tsx, src/pages/profile.tsx, src/stores/OrganizationStore.ts, src/styles/globals.scss, src/styles/profile.module.scss
- 현재 자신이 소속된 조직 표시, x버튼 클릭 시 소속 삭제
- 소속 이름 입력 시 앞 글자가 일치하는 소속명 추천 , 드롭 다운 메뉴에 표시
- 드롭 다운 메뉴 클릭 시 해당 값 불러오기
- 소속 이메일 형식과 타이핑한 이메일 형식이 다르면 에러 메세지 출력
- 이메일 형식이 같을 경우 에러 메세지 없애고 이메일 전송 버튼 활성화
- 이메일이 khaerim41@naver.com을 제외한 다른 이메일로는 전송이 안됨 . 이슈 추가하겠음
https://user-images.githubusercontent.com/56541313/233284409-a87c7eb6-c882-4ec2-a076-bbde6d2dccf2.mov
=> [CFRS-221] 프로필 소속 추가 UI

src/repository/crop.repository.ts
- 작물을 위해서 사용하는 *연속 공부 일수 계산, 평균 공부시간 계산* 쿼리문을 UTC기준 시간을 사용하도록 수정했습니다. DB에서 한국 시간대(UTC+9)를 사용하기 때문에 디비에서 가져온 Date 객체는 KST(UTC+9)로 되어있습니다. 하지만 DB에 실제로 저장되는 Date 인스턴스들의 값은 `UTC`시간대입니다. 따라서 쿼리문에서는 `AT TIMEZONE 'UTC'`를 사용하여 시간대를 일치시켜 쿼리하도록 했습니다.(raw 쿼리할때 자동으로 KST에서 UTC로 변환이 안되더군요.)
테스트한 값들은 노션에서 작물 수확 PATCH API의 하단부에 있씁니다!
- 또한 `${minusUsingStandardHourText}` (갱신 기준시인 06시 값 = '-6 hours') 값이 raw 쿼리문에 제대로 들어가지 않는 문제를 
```
${Prisma.raw(`'${minusUsingStandardHourText}'`)}
````
로 해결했습니다.
=> 작물 관련 쿼리문 UTC 기준 시간 사용하도록 수정

src/models/user/User.ts, src/repository/user.repository.ts
- User에 profileImage 추가
- users/[userId] Get에 유저 프로필 추가하여 반환
=> [CFRS-256] 유저 GET API에 유저 프로필 추가

src/controller/user.controller.ts, src/models/user/User.ts, src/repository/user.repository.ts
- User에 requestHistory 포함
- users/[userId] 에 친구 상태 포함하여 전송
=> [CFRS-257] 프로필 GET API에 친구 상태 포함

src/controller/user.controller.ts, src/repository/user.repository.ts
=> [CFRS-259] 프로필 GET API에 requesterId param 추가

src/repository/crop.repository.ts
- 공부 기록이 다른 월을 포함하는 경우 쿼리 안되던 문제 수정(ex: 4월 30일, 5월 1일 기록이 있는 경우 1로 반환되던 문제)
- 첫 공부 기록이 startDate 날짜와 다른 경우 연속 공부일은 0이나 그렇지 않게 계산하던 문제 수정. 예를 들어 2022-04-19 05:00에 작물을 심고 2022-04-19 06:00에 공부를 시작한 경우 연속 공부일은 0이다. 왜냐하면 4-18에 심었고(-6시간 보정) 4-18에 공부한 기록이 없기 때문이다.
이 쿼리는 Postgres SQL을 사용하여, 사용자의 일별 공부 이력을 조회하고, 이력이 연속적으로 몇일간 이어졌는지 찾는 쿼리입니다. 
쿼리는 다음과 같은 세 부분으로 구성됩니다. 
```SQL
WITH study_dates AS (
SELECT DISTINCT DATE(sh.join_at AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Seoul' + interval '-6 hours') AS date
FROM study_history sh
WHERE sh.user_id = ${userId}
AND sh.join_at >= (${startDate} AT TIME ZONE 'UTC')
AND sh.join_at < (${endDate} AT TIME ZONE 'UTC')
),
```
`WITH` 문은 임시 테이블인 study_dates를 정의합니다. 이 테이블은 일별 공부 이력의 날짜를 모두 포함합니다. `study_history` 테이블에서 사용자 id가 `${userId}`와 일치하고, `join_at` 필드가 …
=> 연속 공부일 계산 함수 문제 수정

src/models/user/User.ts, src/repository/user.repository.ts, src/stores/ProfileStore.ts
응답에 연속 공부일수를 추가했습니다. KST와 하루 끝 시간을 06시 기준으로 계산합니다.
=> [CFRS-261] 프로필 GET API 응답에 연속 공부일 속성 추가

src/pages/friends.tsx, src/stores/FriendStore.ts, src/styles/friend.module.scss
- 친구 요청 목록 UI 구현
-친구 옵션 다이얼로그 구현
https://user-images.githubusercontent.com/56541313/235661171-f6bff310-92a0-41fc-b319-eebd49bca25c.mov
=> [CFRS-246] 친구 리스트 페이지 UI 완성

.dockerignore, .github/workflows/build.yml, .github/workflows/docker-deploy.yml, dockerfile
- main 브런치에 push되는 경우 자동배포가 진행됩니다.
- 앞으로는 배포용 환경변수를 수정하면 깃헙 시크릿에 ENV만 갱신하면 됩니다. .env를 통째로 넣으시면 됩니다.
- 배포해보니 공부방 접속이 안됩니다. 
```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')
(익명 함수) ([roomId]-8bdc785edbde122a.js:1:18512)
```
=> [CFRS-266] 자동 배포 구현

src/styles/friend.module.scss
- 코드 부분적으로 삭제돼서 문제가 생긴거여서 다시 복구 했습니다.
=> [CFRS-217] friend.module.scss 파일 에러 수정

src/controller/room.controller.ts, src/repository/room.repository.ts
이미지를 업로드만 해놓고 실제 DB에서 방을 업데이트하지 않는 문제를 수정했습니다.
=> 방 썸네일 업로드 API 실제 방 DB 갱신 안하는 문제

next.config.js
=> [CFRS-272] 도메일 CORS 에러 (2)

package-lock.json, package.json, src/components/ButtonHoverInfo.tsx, src/components/TimerSettingDropDown.tsx, src/pages/_document.tsx, src/pages/studyRoom.tsx, src/styles/globals.scss, src/styles/studyRoom.module.scss, src/styles/timerSettingDropDown.module.scss
- 기능을 제외한 UI 구현 (기능 포함한 Pr 만들어서 올리겠습니다.)
https://github.com/Foundy-LLC/camstudy-web/assets/56541313/2f77ef0a-3327-4c3d-8483-bfc61594de6a
=> [CFRS-55] 공부방 UI 구현 (기능 x)

next.config.js, src/components/Header.tsx, src/components/ThemeModeToggleButton.tsx, src/components/UserProfileImage.tsx, src/styles/base/_reset.scss, src/styles/darkModeToggleButton.module.scss, src/styles/globals.scss, src/styles/header.module.scss
- 상단 로고 클릭 시 대쉬보드로 이동하도록 변경
- 최근 입장한 방 버튼 커서 변경, 방 이름 다이얼로그로 표시하도록 변경
- 상단 프로필 css 수정
- 다크 모드 적용
https://github.com/Foundy-LLC/camstudy-web/assets/56541313/6bcbbba8-0521-477e-bed7-18d23a0a2625
=> [CFRS-277] 헤더 수정

package-lock.json, src/pages/profile.tsx, src/stores/ProfileStore.ts, src/styles/profile.module.scss
- 프로필 페이지에 현재 입력 값 표시되도록 변경
- 이미지, 닉네임, 자기소개 중 하나라도 입력 값이 바뀌면 저장 버튼, 되돌리기 버튼 활성화
- 프로필 이미지 업로드 하여 프로필 저장 버튼 클릭 시 링크 db에 저장
- 프로필 이미지가 바뀌어도 주소값이 같아 캐쉬가 저장되어 있어 바로 반영되지 않는 문제
https://github.com/Foundy-LLC/camstudy-web/assets/56541313/b612c365-5f90-459a-b1a0-b89baf3a1175
=> [CFRS-282] 프로필 페이지 편집

.gitignore, src/components/ProfileDialog.tsx, src/components/friendRequestButton/RequestedButton.tsx, src/pages/friends.tsx, src/pages/users.tsx, src/stores/FriendStore.ts, src/styles/friend.module.scss, src/styles/searchUser.module.scss
- 친구 목록, 유저 검색에 옵션 다이얼로그 추가
- 프로필 보기 옵션 추가
- 표시할 내용 없을 시 보이는 텍스트 크기, 색 통일
https://github.com/Foundy-LLC/camstudy-web/assets/56541313/16e9228d-9875-4b41-82a5-18673acab916
=> [CFRS-281] 친구 목록, 유저 검색 UI 수정

src/components/ProfileDialog.tsx, src/pages/crop.tsx, src/stores/RoomListStore.ts, src/styles/profileDialog.module.scss
=> 프로필 다이얼로그 작물 이미지 추가

src/constants/roomMessage.ts, src/controller/room.controller.ts, src/models/room/RoomGetRequestBody.ts, src/pages/api/rooms/[roomId].ts, src/pages/rooms/[roomId].tsx, src/repository/room.repository.ts, src/service/room.service.ts, src/stores/RoomListStore.ts
- 공부방 roomId를 이용해서 공부방 한개의 정보를 가져오는 api를 만들었습니다
=> [CFRS-285] 공부방 GET API 구현

src/components/PagenationBar.tsx, src/pages/rank.tsx, src/service/rank.service.ts, src/stores/RankStore.ts, src/styles/globals.scss, src/styles/header.module.scss, src/styles/rank.module.scss
- 내 랭킹, 다른 회원 랭킹 분리해 디자인
- 옵션 버튼 다이얼로그 다른 곳 클릭 시 없어지도록 수정, 디자인 수정
- 페이지네이션, 소속 버튼 밖으로 뺌
- 도움말 다이얼로그 추가 
https://github.com/Foundy-LLC/camstudy-web/assets/56541313/6869fdf2-29a4-4ce7-a6a4-fbc8b992dee0
=> [CFRS-288] 랭킹 화면 ui 수정

src/components/ProfileDialog.tsx, src/pages/crop.tsx, src/pages/index.tsx, src/pages/rooms.tsx, src/stores/RankStore.ts, src/styles/dashboard.module.scss, src/styles/index.module.scss, src/styles/room-list.module.scss
- 메인 화면 ui 크기 조정
-  대쉬보드 실제 데이터로 대체
- 내 작물 없을 때도 작물 폼 표시되도록 수정
https://github.com/Foundy-LLC/camstudy-web/assets/56541313/a01ad0c3-40bc-44b9-9ff4-7510adb80777
=> [CFRS-279] 홈 화면 수정

src/components/SideMenuBar.tsx, src/pages/friends.tsx, src/pages/index.tsx, src/styles/dashboard.module.scss, src/styles/friend.module.scss, src/styles/index.module.scss, src/styles/profile.module.scss, src/styles/sideMenuBar.module.scss
- 사이드 메뉴 색상 변경
- 푸터 내용 추가
- 다크 모드 적용 안된 ui 색상들 수정
https://github.com/Foundy-LLC/camstudy-web/assets/56541313/2cc0d340-8c65-41cb-b324-1ef943b72d64
=> [CFRS-295] 사이드 메뉴 ui 수정

src/components/TimeToString.tsx, src/pages/rank.tsx, src/styles/organizationSelectButton.module.scss, src/styles/rank.module.scss
- 랭킹 시간 표기법 변경, 상단 설명 추가
- 페이지네이션 배경값 변경
- 상단 소속 다크모드 글씨색 변경
=> [CFRS-308] 랭킹 화면 ui 수정

src/components/Header.tsx, src/pages/crop.tsx, src/pages/rank.tsx, src/styles/crop.module.scss, src/styles/friend.module.scss, src/styles/globals.scss, src/styles/header.module.scss, src/styles/profile.module.scss, src/styles/rank.module.scss, src/styles/searchUser.module.scss, src/styles/sideMenuBar.module.scss
=> [CFRS-373] 다크 모드 색상 변경

src/components/ProfileDialog.tsx, src/constants/message.ts, src/constants/tag.constant.ts, src/controller/tag.controller.ts, src/pages/profile.tsx, src/repository/room.repository.ts, src/stores/ProfileStore.ts, src/styles/profile.module.scss, src/styles/profileDialog.module.scss
- 방 GET API 최신순으로 정렬하여 반환하도록 변경
- 프로필 페이지에서 닉네임, 자기 소개 길이 제한
- 프로필 페이지 닉네임 input에 입력 값 없을 때 저장 버튼 비활성화, 에러 메세지 출력
- 프로필 태그 버그 해결
- 프로필 다이얼로그 친구 요청 상태 버튼 ui 수정
=> [CFRS-325] 남은 버그 수정 (P0)

.gitignore
=> `uploads` 폴더에 `.gitkeep` 파일 추가하여 폴더 유지하도록 수정

prisma/schema.prisma, src/repository/room.repository.ts
- prisma를 pull 하였습니다.
- expired_at 값들을 created_at으로 임시적으로 옮겨두었습니다.
=> [CFRS-384] room 테이블에 create_at 추가, 방 GET API created_at 순으로 정렬

src/pages/rooms.tsx, src/styles/room-list.module.scss
- 공부방 리스트 더보기 버튼 삭제
- 버튼 색상 변경
- 비밀방 아이콘 위치, 색상 변경
=> [CFRS-386] 공부방 리스트 UI 수정

src/styles/profileDialog.module.scss
=> [CFRS-388] 친구 취소 버튼 색상 변경

src/pages/friends.tsx, src/pages/users.tsx, src/styles/friend.module.scss, src/styles/searchUser.module.scss
- 친구 useroverview 폼 마우스 오버 시 색상 변경
- 친구 폼 클릭 시 프로필 다이얼로그 나오도록 변경
- 친구 리스트 버튼 마우스 오버 시 색상 변경
- 필요없는 옵션 버튼은 삭제
- 기본 프로필 디자인 변경
=> [CFRS-387] 친구 목록 프로필 페이지 ui 개선

src/components/WaitingRoom.tsx, src/pages/rooms/[roomId].tsx, src/styles/studyRoom.module.scss, src/styles/watingRoom.module.scss
- 준비 화면, 공부방 화면 방 나가기 버튼 ui 추가
=> [CFRS-393] 방 나가기 버튼 추가
